version: '3.1'

services:
# the database we use
  mongo:
    container_name: ubiss_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
     - ./containers/mongo/data:/data/db
     - ./containers/mongo/config:/data/configdb
    networks:
      ubiss:
        ipv4_address: 172.20.0.19


  subscriber:
    container_name: ubiss_subscriber
    build:
      context: ./subscriber
      dockerfile: subscriber/Dockerfile
    restart: always
    volumes:
      - ./containers/mqtt/files:/home/files 
    networks:
      ubiss:
        ipv4_address: 172.20.0.24
    command: /bin/bash -c "cd /home && ls && sleep 5 && python3 subscriber.py"

  mongo-express:
    container_name: ubiss_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      ubiss:
        ipv4_address: 172.20.0.20

# Generic filehosting for extracted data from the database
  file_hosting:
    container_name: ubiss_fileserver
    image: halverneus/static-file-server:latest
    ports:
     - 9080:8080
    volumes:
      - ./containers/mqtt/files:/web 
    networks:
      ubiss:
        ipv4_address: 172.20.0.21

# MQTT broker
  mosquitto:
    container_name: ubiss_mosquitto
    image: eclipse-mosquitto
    volumes:
      - type: bind
        source: ./containers/mosquitto/config/
        target: /mosquitto/config/
      - ./containers/mosquitto/log:/mosquitto/log
      - ./containers/mosquitto/data:/mosquitto/data
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      ubiss:
        ipv4_address: 172.20.0.22

networks:
    ubiss:
        driver: bridge
        name: ubiss_network
        ipam:
            config:
                - subnet: 172.20.0.0/24




