version: '3.1'

services:
# the database we use
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
     - ./mongo/data:/data/db
    networks:
      ubiss:
        ipv4_address: 172.20.0.19


  subscriber:
    image: subscriber:latest
    restart: always
    volumes:
      - /home/andreaswork/project/ubiss2023-iot/mqtt/files:/home/files 
    networks:
      ubiss:
        ipv4_address: 172.20.0.24
    command: /bin/bash -c  "cd /home && ls && sleep 5 && python subscriber.py"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
      #- 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      ubiss:
        ipv4_address: 172.20.0.20

# Generic filehosting for extracted data from the database
  file_hosting:
    image: halverneus/static-file-server:latest
    ports:
     - 9080:8080
    volumes:
      - /home/andreaswork/project/ubiss2023-iot/mqtt/files:/web 
    networks:
      ubiss:
        ipv4_address: 172.20.0.21

# MQTT broker
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      ubiss:
        ipv4_address: 172.20.0.22

volumes:
  data:
    name: "mqtt-broker-data"

networks:
    ubiss:
        driver: bridge
        name: ubiss_network
        ipam:
            config:
                - subnet: 172.20.0.0/24


#docker run -it -p 1883:1883 -p 9001:9001 -v /home/andreaswork/project/ubiss2023-iot/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf -v /mosquitto/data -v /mosquitto/log eclipse-mosquitto


